# -*- coding: utf-8 -*-
"""Aula24maio2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3Nkw2VvbQF59FC-x6TOigPx8GorfVx7

#Python com Framework
## Prof. Tom
"""

a = 1
# Declara primeira variável

b = 2

print( a+b)

a1 = int(input('Digite o primeiro número: '))

if a1 >= 10:
  print('OK')
elif a1 >= 8 and a1 >= 9:
  print('Quase lá!')
else:
  print('Não foi dessa vez')

"""#Jogo de Futebol"""

#Desenvolva um programa que receba do usuário, o placar de um jogo de futebol( os gols de cada time) e informa se o resultado foi um empate, se a vitória foi do primeiro ou segundo time

time1 = int(input('Quantos gols fez o time1: '))
time2 = int(input('Quantos gols fez o time2: '))

if time1 > time2:
  print(f'Vitória do time1 por {time1} x {time2}')
elif time2 > time1:
  print(f'Vitória do time2 por {time2} x {time1}')
else:
  print('Os times empataram...')

"""#Programa de compras"""

#Crie um programa que receba um valor de uma compra e receba o número de prestações sem juros

valor_compra = float(input('Qual valor foi a sua compra: R$'))
quantidade_parcelas = int(input('Quantidade de parcelas: '))

total = valor_compra / quantidade_parcelas

print(f'O valor da compra foi de R${valor_compra} e ficou parcelado em {quantidade_parcelas} no valor de R$ {total}')

"""#Classificação de idade"""

#Pegar idade do usuário e classificar nas seguintes categorias
'''INfantil A = 5 a 7 anos
Infantil B = 8 a 11 anos
Juvenil A = 12 a 13 anos
Juvenil B = 14 a 17 anos
Adultos = Maiores de 18 anos'''

idade = int(input('Digite sua idade para obter sua categoria: '))

if idade >= 5 and idade <=7:
  print('Sua categoria é: INFANTIL A')
elif idade >= 8 and idade <= 11:
  print('Sua categoria é: INFANTIL B')
elif idade >= 12 and idade <=13:
  print('Sua categoria é: JUVENIL A')
elif idade >= 14 and idade <= 17:
  print('Sua categoria é: JUVENIL B')
elif idade >= 18:
  print('Você é maior de idade!')

"""# Programa com decimais

"""

'''Solicitar dois números ao usuário e informa o resultado
das quatro operações (Subtração, Multiplicação, divisão e adição)'''

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

subtracao = n1 - n2
adicao = n1 + n2
multiplicacao = n1 * n2
divicao = n1 / n2

print(f'A subtração de {n1} - {n2} é: {subtracao}')
print(f'A soma de {n1} + {n2} é: {adicao}')
print(f'A multiplicação de {n1} x {n2} é: {multiplicacao}')
print(f'A divisão entre {n1} / {n2} é: {divicao}')

"""#Calculo de Reservatório"""

#Assuna que o reservatório está cheio, tenha formato cubico e informe:

#A - A capacidade total do reservatório

#B - A autonomia do reservatório, em dias

#C - A classificação do consumo, de acordo com a quantidade de dias de autonomia
#Consumo elevado, se autonomia for menor que 2 dias
#Consumo moderado, se autonomia estiver entre 2 a 7 dias
#Consumo reduzido, se a autonomia maior que 7 dias.

altura = float(input('Digite a altura do reservatório: '))
largura = float(input('Digite a largura do reservatório: '))
comprimento = float(input('Digite o comprimento do reservatório: '))
consumo_medio = float(input('Consumo diário L/dia: '))

#Calcular a capacidade do reservatório
volume = altura * largura * comprimento
capacidade = volume * 1000

litros = consumo_medio * 1000

#Calcular a autonomia em dias de uso
autonomia =  capacidade / litros




print(f'A capacidade total do reservatório é de: {capacidade}')
print(f'A autonomia do do reservatório é de {autonomia}')

if autonomia < 2:
  print('Consumo elevado')
elif autonomia >= 2 and autonomia <= 7:
  print('Consumo moderado')
else:
  print('Consumo reduzido')