# -*- coding: utf-8 -*-
"""aula_senaipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzchfRXPE096gor2HCuW0SCPcZLPEFky
"""

#1
timeA = int(input("Quantos gols fez o primeiro time : "))
timeB = int(input("Quantos gols fez o segundo time : "))
if timeA == timeB:
  print("Empate")
elif timeA > timeB:
  print("Vitoria do time A")
else:
  print("Vitoria do time B")

#2
valor_produto = float(input("Digite o valor do produto : "))
prestacoes = int(input("Digite em quantas prestações: "))

print(f"O valor em {prestacoes} prestações foi de R$ {valor_produto/prestacoes:.2f}")

#3
idade = int(input("Digite sua idade : "))
if idade >=18:
  print("Adultos")
if idade >=14 and idade <=17:
  print("Juvenil B")
if idade >=12 and idade <=13:
  print("Juvenil A")
if idade >= 8 and idade <=11:
  print("Infantil B")
if idade >=5 and idade <=7:
  print("Infantil A")

#4
a = float(input("Digite um número : "))
b = float(input("Digite um número : "))

print(f"Adição {a+b:.2f}")
print(f"Subtração {a-b:.2f}")
print(f"Multiplicação {a*b:.2f}")
print(f"Divisão {a/b:.2f}")

altura = float(input("Digite a altura: "))
largura = float(input("Digite a largura : "))
comprimento = float(input("Digite o comprimento : "))

consumo = float(input("Digite o consumo médio diário em litros/dia: "))


reservatorio = altura * largura * comprimento
litros = reservatorio / 1000


dias = litros/consumo

if dias < 2:
    print("Consumo elevado")
elif 2 <= dias <= 7:
     print("Consumo moderado")
else:
    print("Consumo reduzido")

print(f"Capacidade total do reservatório: {litros} litros")
print(f"Autonomia do reservatório: {dias:.2f} dias")