# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cC16wTXnp5sctNT98LcLapt23y91udgB
"""

#Exercicio I
a1=int(input("Digite o placar do primeiro time:"));
b1=int(input("Digite o placar do segundo time:"));

if a1>b1:
  print("Vitória do primeiro time!")
elif b1>a1:
  print("Vitória do segndo time!");
else:
  print("Jogo deu empate!");

#Exercicio II

valorComopra=int(input("Digite o valor da compra: "));
qprestacoes=int(input("Digite a quantidade de prestações: "));

print(valorComopra/qprestacoes);

#Exercicio III

idade=int(input("Digite a idade do nadador: "));

if idade>=5 and idade<=7:
  print("Nadador da categoria Infantil A.");
elif idade>=8 and idade<=11:
  print("Nadador da categoria Infantil B.");
elif idade>=12 and idade<=13:
  print("Nadador da categoria Juvenil A.");
elif idade>=14 and idade<=17:
  print("Nadador da categoria Juvenil B.");
elif idade>=18:
  print("Nadador categoria Adulto.");
else:
  print("Não a categoria para esta idade.");

#Exercicio IV

n1=float(input("Insira o primeiro numero: "));
n2=float(input("Insira o segundo numero: "));

rSub=(n1-n2);
rDiv=(n1/n2);
rMult=(n1*n2);

pontos=int(0);

sub=float(input(f"Digite o valor de {n1}-{n2}: "));
if sub==rSub:
  pontos=pontos+1
  print("Correto!");
else:
  print(f"Incorreto o valor certo é {rSub}");

div=float(input(f"Digite o valor de {n1}/{n2}: "));
if div==rDiv:
  pontos=pontos+1
  print("Correto!");
else:
  print(f"Incorreto o valor certo é {rDiv}");

mult=float(input(f"Digite o valor de {n1}*{n2}: "));
if mult==rMult:
  pontos=pontos+1
  print("Correto!");
else:
  print(f"Incorreto o valor certo é {rMult}");

print(f"Voce acertou {pontos} de 3 questões.")

from typing import Mapping
def main():

  altura=float(input("Digite a altura do reservatorio (em cm):  "))
  largura=float(input("Digite a largura do reservatorio (em cm):  "))
  comprimento=float(input("Digite a comprimento do reservatorio (em cm):  "))
  consumoMedio=float(input("Digite o consumo medio de litros por dia:  "))

  volumeCm3=altura*largura*comprimento
  volumeLitros=volumeCm3/1000.0

  autonomia=volumeLitros/consumoMedio

  print(f"Capacidade total do reservatório: {volumeLitros:.2f} litros")
  print(f"Autonomia do reservatório: {autonomia:.2} dias")

  if autonomia<=32:
    classificacao="consumo elevado."
  elif autonomia <=7:
    classificacao="consumo moderado."
  else:
    classificacao="consumo reduzido."

  print(f"Classificação de {classificacao}");

if __name__=="__main__":
  main()
