# -*- coding: utf-8 -*-
"""exercicios001_24052025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZcLhZ6vQQJETV0Zeg_KFy5x8Y2pdsUY

Exercícos Aula 24 de maio
"""

'''
Desenvolva um programa que recebe do usuário o placar de um jogo de futebol
(os gols de cada time) e informe se o resultado foi empate, se a vitória do time 1 ou vitória do time 2
'''


time1 = 'São Paulo'
time2 = 'Flamengo'

gols1 = int(input(f'Informe quantos gols o time {time1} fez! '))
gols2 = int(input(f'Informe quantos gols o time {time2} fez! '))

placar = (f'Placar: {time1} {gols1} x {gols2} {time2}')

if (gols1 > gols2):
  print(f'{time1} venceu! {placar}')
elif(gols1 < gols2):
  print(f'{time2} venceu! {placar}')
else:
  print(f'Enpate! {placar}')

'''
Faça um algoritmo que receba um valor de uma compra e receba o numero de parcelas. Apresente o valor das prestações sem juros.
'''
valor_compra = float (input('Digite o valor da compra '))

parcelas = int(input('Quantas parcelas ? '))

valor_parcelas = (valor_compra / parcelas)

print(f'Valor Total: R$ {valor_compra:.2f}\nQuantidade de parcelas {parcelas}\nValor de cada parcela: R$ {valor_parcelas:.2f}')

'''
Elabore um algoritmo que dada a idade de um nadador classifique-o em uma das seguintes categorias

- infantil A = 5 a 7 anos
- infantil B = 8 a 11 anos
- Juvenil A = 12 a 13 anos
- Juvenil B = 14 a 17 anos
- Adultos = Maiores de 18
'''

idade = 0

while True:

  idade = int (input('Informe sua idade: '))

  if idade >= 5:

    if idade >= 5 and idade <= 7:
        print(' Sua categogia é infantil A')
    elif idade >= 8 and idade <= 11:
        print(' Sua categogia é infantil B')
    elif idade >= 12 and idade <= 13:
        print(' Sua categogia é Juvenil A')
    elif idade >= 14 and idade <= 17:
        print(' Sua categogia é Juvenil B')
    elif idade >= 18:
        print(' Sua categogia é Adulto')
    break
  else:
    print(f'{idade} anos de idade ainda não tem categoria.')

num1 = float(input('Insira o 1º número '))
num2 = float(input('Insira o 2º número '))

adicao = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2

print(f'''
  Adição : {adicao:.0f}
  Subtração: {subtracao:.0f}
  Multiplicação: {multiplicacao:.0f}
  Divisão: {divisao:.2f}
''')

altura = float(input('Qual a altura do reservatório em cm? '))
largura = float(input('Qual a largura do reservatório em cm? '))
comprimento = float(input('Qual o comprimento do reservatório em cm? '))


consumo = float(input('Qual o consumo diário médio em litros por pessoa? ')) # Consumo médio diário em litros / dia


resposta = 'Consumo de água'

capacidade_reservatorio = (altura * largura * comprimento) / 1000
autonomia =  (capacidade_reservatorio / consumo)

print(f'''
A capacidade do reservatório e de {capacidade_reservatorio:.0f} litros.
Autonomia do reservatorio é de {autonomia:.0f} dias.
''')

if autonomia  < 2:
  print(f'ALERTA!\n{resposta} Elevado!')
elif autonomia >= 2 and autonomia <= 7:
  print(f'{resposta} moderado.')
else:
  print(f'{resposta} reduzido.')