# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMyAYxY0OYcLFRXcgk8VLwfq_-BIbbhL
"""

#Exercício I
TimeA=int(input("Digite o valor compra: "));
TimeB=int(input("Digite o placar primeiro time: "));

if TimeA > TimeB:
  print('Time A vencedor');
elif TimeA < TimeB:
  print('Time B Vencedor');
else:
  print('Equipes empatadas')

#Exercício II
vCompra=int(input("Digite o valor compra: "));
nPresta=int(input("Digite o valor prestações: "));

print(vCompra/nPresta)

#Exercício III

vCategoria=int(input("Digite a idade: "));

if vCategoria>=5 and vCategoria<=7:
  print('Categoria Infantil A');
elif vCategoria>=8 and vCategoria<=11:
  print('Categoria Infantil B');
elif vCategoria>=12 and vCategoria<=13:
  print('Categoria Juvenil A');
elif vCategoria>=14 and vCategoria<=17:
  print('Categoria Juvenil B');
elif vCategoria>=18:
  print('Categoria Adultos');
else:
  print('Não temos categoria para essa idade!')

#Exercício IV

vValor1=float(input("Digite um valor1: "));
vValor2=float(input('Digite um valor2: '));
vponto=int(10)
vResSubC=(vValor1-vValor2);
vResDivC=(vValor1/vValor2);
vResMutC=(vValor1*vValor2);
vResAdiC=(vValor1+vValor2);

vResSubU=float(input(f'Digite o valor de {vValor1} - {vValor2}: '))

if vResSubC == vResSubU:
  print('Correto');
  ponto=vponto

else:
  print('Incorreto')

vResDivU=float(input(f'Digite o valor de {vValor1} / {vValor2}: '))

if vResDivC == vResDivU:
  print('Valor está Correto!');
  ponto=ponto+vponto
else:
  print('Valor está Incorreto!')

vResMutU=float(input(f'Digite o valor de {vValor1} * {vValor2}; '))

if vResMutC == vResMutU:
  print('Valor está Correto!');
  ponto=ponto+vponto
else:
  print('Valor está Incorreto!')

vResAdiU=float(input(f'Digite o valor de {vValor1} + {vValor2}: '))

if vResAdiC == vResAdiU:
  print('Valor está Correto!');
  ponto=ponto+vponto
  print(f'Sua pontuação é: {ponto}')
else:
  print('Valor está Incorreto!')

#Desafio Bonus
def main():
    # Entrada dos dados
    altura = float(input("Digite a altura do reservatório (em cm): "))
    largura = float(input("Digite a largura do reservatório (em cm): "))
    comprimento = float(input("Digite o comprimento do reservatório (em cm): "))
    consumo_diario = float(input("Digite o consumo médio diário (em litros): "))

    # Cálculo do volume em cm³ (1 litro = 1000 cm³)
    volume_cm3 = altura * largura * comprimento
    volume_litros = volume_cm3 / 1000.0

    # Cálculo da autonomia em dias
    autonomia = volume_litros / consumo_diario

    # Resultados
    print("\n--- RESULTADOS ---")
    print(f"Capacidade total do reservatório: {volume_litros:.2f} litros")
    print(f"Autonomia do reservatório: {autonomia:.2f} dias")

    # Classificação do consumo
    if autonomia < 2:
        classificacao = "Consumo elevado"
    elif autonomia <= 7:
        classificacao = "Consumo moderado"
    else:
        classificacao = "Consumo reduzido"

    print(f"Classificação do consumo: {classificacao}")

if __name__ == "__main__":
    main()